language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env: TEST_SUITE=test-main
matrix:
  include:
  - python: "3.6"
    env: TEST_SUITE=lint
install:
  - pip install codecov
  - tools/provision
  - source zulip-api-py*-venv/bin/activate
script:
  - tools/$TEST_SUITE
after_success:
  - codecov -v
  - cat asdf
